from tkinter import *
from tkinter.ttk import *
m=Tk()
m.title('Simple Calculator')
m.geometry("450x300")
num1_var=StringVar()
num2_var=StringVar()
def Sum():
   num1=num1_var.get()
   num2=m=num2_var.get()
   print("The num 1 is ",num1)
   print("The num 2 is ",num2)
   print("The Sum is ",int(num1)+int(num2))
   num1_var.set("")
   num2_var.set("")
def Sub():
   num1=num1_var.get()
   num2=m=num2_var.get()
   print("The num 1 is ",num1)
   print("The num 2 is ",num2)
   print("The Subtraction is: ",int(num1)-int(num2))
   num1_var.set("")
   num2_var.set("")
def Mul():
   num1=num1_var.get()
   num2=m=num2_var.get()
   print("The num 1 is ",num1)
   print("The num 2 is ",num2)
   print("The Multiplication is: ",int(num1)*int(num2))
   num1_var.set("")
   num2_var.set("")
def Div():
   num1=num1_var.get()
   num2=m=num2_var.get()
   print("The num 1 is ",num1)
   print("The num 2 is ",num2)
   print("The Division is ",int(num1)/int(num2))
   num1_var.set("")
   num2_var.set("")
l = Label(m, text="Simple Calculator")
l1=Label(m,text="Number1: ")
l2=Label(m,text="Number2: ")
t1=Entry(m,width=30, font=('calibre',10,'normal'),textvariable=num1_var)
t2=Entry(m,width=30, font=('calibre',10,'normal'), textvariable=num2_var)
b1=Button(m,text="Sum", command=Sum)
b2=Button(m,text="Sub", command=Sub)
b3=Button(m,text="Mul", command=Mul)
b4=Button(m,text="Div", command=Div)
b5=Button(m,text="exit",command=m.destroy)
l.grid(row = 0, column = 0,  pady = 2)
l1.grid(row = 1, column = 0,  pady = 2)
t1.grid(row = 1, column = 1,  pady = 2)
l2.grid(row = 2, column = 0,  pady = 2)
t2.grid(row = 2, column = 1,  pady = 2)
b1.grid(row = 3, column = 0,  pady = 2)
b2.grid(row = 3, column = 1,  pady = 2)
b3.grid(row = 4, column = 0,  pady = 2)
b4.grid(row = 4, column = 1,  pady = 2)
b5.grid(row = 5, column = 0,  pady = 2)
m.mainloop()