from tkinter import *
m = Tk() 
m.geometry("450x300") 
m.title("User Interface")
name_var=StringVar()
passw_var=StringVar()
def submit():
    name=name_var.get()
    password=passw_var.get()
    print("The name is : " + name)
    print("The password is : " + password)
    name_var.set("")
    passw_var.set("")
l1 = Label(m, text = "Username")
l2 = Label(m, text = "Password")
t1 = Entry(m,width = 30, textvariable = name_var)
t2 = Entry(m, width = 30, textvariable = passw_var, show = "*")
b1 = Button(m, text = "Submit", command = submit)
l1.place(x = 40,y=60)
t1.place(x = 110,y = 60)
l2.place(x = 40,y=100)
t2.place(x = 110, y=100)
b1.place(x = 40,y=130)
m.mainloop()