employee_name=str(input("Enter the name of the employee: "))
employee_id=int(input("Enter the employees ID: "))
employee_dep=str(input("Enter the employees department: "))
salary=int(input("Enter the salary of the employee: "))
print("*****The profile of the employee is*******")
print(f"employee name: {employee_name}")
print(f"employee id: {employee_id}")
print(f"employee_dep: {employee_dep}")
print(f"employee salary: {salary}")