name=str(input("Enter user name: "))
age=int(input("Enter the age of the user: "))
class10=str(input("Enter which school (in 10th): "))
class12=str(input("Enter which school (in 12th): "))
hobby=str(input("Enter user's Hobbies: "))
achievements=str(input("Enter  user's Achievemnets: "))
email=str(input("Enter user's Email Id: "))
phoneno=int(input("Enter user's Phone number: "))
address=str(input("Enter user's Address: "))
print("PERSONAL PROFILE")
print("----------------------------------------")
print("Name: ",name)
print("Age: ",age)
print("10th School: ",class10)
print("12th School: ",class12)
print("Hobbies: ",hobby)
print("Achievements: ",achievements)
print("Email Id: ",email)
print("Phone Number: ",phoneno)
print("Address :",address)