name=str(input("Enter the user name: "))
age=int(input("Enter the age: "))
email=str(input("Enter user's Email Id: "))
role=str(input("Enter user's role: "))
salary=int(input("Enter user's salary: "))
print("PERSONAL PROFILE")
print("----------------------------------")
print("Name: ",name)
print("Age: ",age)
print("Emailid: ",email)
print("Role: ",role)
print("Salary: ",salary)