flightno=str(input("Enter the flight number: "))
departurecity=str(input("Enter the Departure city: "))
arrivalcity=str(input("Enter the arriavlcity: "))
departuretime=str(input("Enter the departure time: "))
print("DETAILS OF THE FLIGHT")
print("------------------------------")
print("Flight number: ",flightno)
print("departure city: ",departurecity)
print("Arrival city: ",arrivalcity)
print("Departure Time:",departuretime)